name: Gitlab Stats update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout emochka2007 repository
        uses: actions/checkout@v2
        with:
          path: 'emochka2007'

      - name: Checkout gitlab-stats repository
        uses: actions/checkout@v2
        with:
          repository: 'emochka2007/gitlab-stats'
          token: ${{ secrets.GITHUB_TOKEN }}   # Use a GitHub Secret for the token
          path: 'gitlab_stats'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build and run Rust application
        run: cargo run > ../emochka2007/output.md
        working-directory: gitlab_stats

      - name: Update README
        run: |
            sed -i '/^<!--START_SECTION:emo-gitlab-->$/,/^<!--END_SECTION:emo-gitlab-->/{//!d;}' README.md
            sed -i '/^<!--END_SECTION:emo-gitlab-->/r ./output.md' README.md
        working-directory: emochka2007

      - name: Commit and push changes
        run: |
            git config --global user.name 'emochka2007'
            git config --global user.email 'nikitapoznyakov@gmail.com'
            git add README.md
            git commit -m "Updated README with new stats"
            git push
        working-directory: emochka2007
